// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCfgd-t8Qy1r1k7PMTYeqiyJPGKdr1z7uo',
    appId: '1:32761881815:web:9369368343e7804376fc92',
    messagingSenderId: '32761881815',
    projectId: 'iti-firebase1',
    authDomain: 'iti-firebase1.firebaseapp.com',
    storageBucket: 'iti-firebase1.firebasestorage.app',
    measurementId: 'G-Z5W6BJ5EEB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCtPmDFfpJVbKYqgxE_2YsR8zQoIuW_kgI',
    appId: '1:32761881815:android:151e7fffd550d88f76fc92',
    messagingSenderId: '32761881815',
    projectId: 'iti-firebase1',
    storageBucket: 'iti-firebase1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCUqUAxLM8yFq71gOKZY-xIBsbZe4Ve0aY',
    appId: '1:32761881815:ios:050e876b6da498fe76fc92',
    messagingSenderId: '32761881815',
    projectId: 'iti-firebase1',
    storageBucket: 'iti-firebase1.firebasestorage.app',
    iosBundleId: 'com.example.firebaseProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCUqUAxLM8yFq71gOKZY-xIBsbZe4Ve0aY',
    appId: '1:32761881815:ios:050e876b6da498fe76fc92',
    messagingSenderId: '32761881815',
    projectId: 'iti-firebase1',
    storageBucket: 'iti-firebase1.firebasestorage.app',
    iosBundleId: 'com.example.firebaseProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCfgd-t8Qy1r1k7PMTYeqiyJPGKdr1z7uo',
    appId: '1:32761881815:web:c93c26c00845c24e76fc92',
    messagingSenderId: '32761881815',
    projectId: 'iti-firebase1',
    authDomain: 'iti-firebase1.firebaseapp.com',
    storageBucket: 'iti-firebase1.firebasestorage.app',
    measurementId: 'G-LD4VDXJZGN',
  );
}
